#!/usr/bin/python3
"""A codebase that contains a defined class  of City"""
from sqlalchemy.orm import relationship
from relationship_state import Base, State
from sqlalchemy import Column, Integer, String, ForeignKey

class City(Base):
    """City class inherits from State class
    Links to MySQL table 'cities'
    Attributes:
        id: column of autogenerated unique integer, can't be NULL, primary key
        name: column of string with max 128 characters, can't be NULL
        state_id: column of integer, can't be NULL, foreign key (states.id)
    """
    __tablename__ = 'cities'
    id = Column(Integer, primary_key=True)
    name = Column(String(128))
    state_id = Column(Integer, ForeignKey('states.id'))
